version: 0.0
os: linux
files:
  - source: .
    destination: /home/ubuntu/testing-cicd
hooks:
  ApplicationStop:
    - location: env_setup/stop_server.sh
      timeout: 300
      runas: root
  BeforeInstall:
    - location: env_setup/install_dependancies.sh
      timeout: 300
      runas: root
  ApplicationStart:
    - location: env_setup/start_server.sh
      timeout: 300
      runas: root
  