version: 0.0
os: linux
files:
  - source: .
    destination: /home/ubuntu/testing-cicd
hooks:
  Install:
    - location: /home/ubuntu/testing-cicd/env_setup/cloner.sh
      timeout: 300
      runas: root
  AfterInstall:
    - location: /home/ubuntu/testing-cicd/env_setup/install_dependancies.sh
      timeout: 300
      runas: root
  ApplicationStart:
    - location: /home/ubuntu/testing-cicd/env_setup/start_server.sh
      timeout: 300
      runas: root
  