name: test CI/CD pipeline
on:
  push:
    branches: [master]
  
jobs:
  continuous-integration:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Setting up node js for version 12
        uses: actions/setup-node@v3
        with:
          node-version: '12'
      - name: configuring AWS credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }} 
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY_ID }} 
          aws-region: ${{ secrets.AWS_REGION }}
      - name: Installing dependancies
        run: npm install
      - name: Start Test Server
        run: npm start &
      - name: Exitting the Server Process
        if: always()
        run: |
          kill -f "npm start"

  continuous-deployment:
    runs-on: ubuntu-latest
    needs: [continuous-integration]
    if: github.ref == 'refs/heads/main'
    steps:
      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v1
        with: 
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }} 
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY_ID }} 
          aws-region: ${{ secrets.AWS_REGION }}
      - name: create CodeDeploy Deployment
        id: deploy
        run: |
          aws deploy create-deployment \
            --application-name testCICD \
            --deployment-group-name sample_testing_cicd \
            --deployment-config-name CodeDeployDefault.OneAtATime \
            --github-location repository=${{ github.repository }},commitId=${{ github.sha }}
